title: Lakesh Kumar Suryadevara
author:
  email: "suryadevara.lakeshkumar@gmail.com"  # Replace with your email
  linkedin: "www.linkedin.com/in/lakeshkumarsuryadevara"  # Replace with your LinkedIn URL
#phone: "+1234567890"  # Replace with your phone number
theme: jekyll-theme-minimal
